import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { authenticate, verifyOrigin } from '../../lib/server/auth';
import { GET, POST, PUT } from '../../app/api/[...path]/route';
let directory:string;
beforeEach(async()=>{directory=await fs.mkdtemp(path.join(os.tmpdir(),'classcompass-api-'));vi.stubEnv('LOCAL_DATA_DIR',directory);vi.stubEnv('DATA_BACKEND','local');vi.stubEnv('APP_DEPLOYMENT','local');vi.stubEnv('AI_MODE','fixture');vi.stubEnv('VERCEL','');});
afterEach(async()=>{vi.unstubAllEnvs();await fs.rm(directory,{recursive:true,force:true});});
const context=(parts:string[])=>({params:Promise.resolve({path:parts})});
const jsonRequest=(url:string,value:unknown,headers:Record<string,string>={})=>new Request(url,{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify(value)});
describe('request boundaries',()=>{
 it('marks sample-only tools as enabled in the explicit local fixture backend',async()=>{
  const response=await GET(new Request('http://127.0.0.1:3000/api/classroom'),context(['classroom']));
  expect(response.status).toBe(200);
  expect((await response.json()).data.config.sampleToolsEnabled).toBe(true);
 });
 it('uses the browser HTTP Host when Next has internally rewritten loopback URL',async()=>{const req=jsonRequest('http://localhost:3000/api/uploads/prepare',{}, {host:'127.0.0.1:3000',origin:'http://127.0.0.1:3000','sec-fetch-site':'same-origin'});expect(()=>verifyOrigin(req)).not.toThrow();await expect(authenticate(req)).resolves.toHaveProperty('id');});
 it('rejects cross-origin mutation, opaque origin, forwarded-host bypass and remote local-backend access',async()=>{expect(()=>verifyOrigin(jsonRequest('http://localhost:3000/api/x',{}, {origin:'https://attacker.test'}))).toThrow(/must come from/);expect(()=>verifyOrigin(jsonRequest('http://localhost:3000/api/x',{}, {origin:'null'}))).toThrow();expect(()=>verifyOrigin(jsonRequest('http://localhost:3000/api/x',{}, {origin:'https://attacker.test','x-forwarded-host':'attacker.test'}))).toThrow();expect(()=>verifyOrigin(jsonRequest('http://localhost:3000/api/x',{}, {origin:'http://localhost:3000','sec-fetch-site':'cross-site'}))).toThrow();await expect(authenticate(new Request('http://localhost:3000/api/classroom',{headers:{host:'attacker.test'}}))).rejects.toThrow(/restricted/);});
 it('passes upload idempotency through HTTP and rejects a changed request',async()=>{const url='http://localhost:3000/api/uploads/prepare',input={purpose:'worksheet',templateId:'baseline-template-v1',files:[{name:'work.png',type:'image/png',size:10}]},headers={'idempotency-key':'repeat-upload'};const first=await POST(jsonRequest(url,input,headers),context(['uploads','prepare'])),second=await POST(jsonRequest(url,input,headers),context(['uploads','prepare']));expect(first.status).toBe(201);const a=await first.json(),b=await second.json();expect(a.data.assets[0].id).toBe(b.data.assets[0].id);const conflict=await POST(jsonRequest(url,{...input,files:[{name:'other.png',type:'image/png',size:10}]},headers),context(['uploads','prepare']));expect(conflict.status).toBe(409);expect((await conflict.json()).error.code).toBe('IDEMPOTENCY_CONFLICT');});
 it('enforces finalized-upload immutability at the HTTP boundary',async()=>{const bytes=await fs.readFile('public/demo/baseline-stu-01.png'),prepared=await POST(jsonRequest('http://localhost:3000/api/uploads/prepare',{purpose:'worksheet',templateId:'baseline-template-v1',files:[{name:'work.png',type:'image/png',size:bytes.length}]}),context(['uploads','prepare']));const assetId=(await prepared.json()).data.assets[0].id;const upload=()=>new Request(`http://localhost:3000/api/uploads/${assetId}/content?slot=original`,{method:'PUT',headers:{'content-type':'image/png'},body:new Uint8Array(bytes)});expect((await PUT(upload(),context(['uploads',assetId,'content']))).status).toBe(200);expect((await POST(jsonRequest(`http://localhost:3000/api/uploads/${assetId}/complete`,{}),context(['uploads',assetId,'complete']))).status).toBe(200);const repeat=await PUT(upload(),context(['uploads',assetId,'content']));expect(repeat.status).toBe(409);expect((await repeat.json()).error.code).toBe('UPLOAD_FINALIZED');});
 it('rejects forged file metadata, invalid keys and extra JSON fields before any upload',async()=>{const url='http://localhost:3000/api/uploads/prepare',input={purpose:'worksheet',templateId:'baseline-template-v1',files:[{name:'work.png',type:'image/png',size:10}]};expect((await POST(jsonRequest(url,{...input,ownerId:'another-owner'}),context(['uploads','prepare']))).status).toBe(422);expect((await POST(jsonRequest(url,input,{'idempotency-key':'invalid key'}),context(['uploads','prepare']))).status).toBe(400);const denied=await POST(jsonRequest(url,input,{origin:'https://attacker.test'}),context(['uploads','prepare']));expect(denied.status).toBe(403);});
});
