import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { LocalRepository } from '../../lib/server/repository';
import { finalizeUpload, prepareUploads, putObject } from '../../lib/server/storage';
import { importLesson } from '../../lib/server/imports';
import { curriculum } from '../../lib/curriculum';
import { confirmLessonImport } from '../../lib/domain';
const actor={id:'11111111-1111-4111-8111-111111111111',name:'Teacher'};
let directory:string,repo:LocalRepository;
beforeEach(async()=>{directory=await fs.mkdtemp(path.join(os.tmpdir(),'classcompass-imports-'));vi.stubEnv('LOCAL_DATA_DIR',directory);vi.stubEnv('DATA_BACKEND','local');vi.stubEnv('APP_DEPLOYMENT','local');vi.stubEnv('AI_MODE','fixture');vi.stubEnv('VERCEL','');repo=new LocalRepository(directory,actor.id);});
afterEach(async()=>{vi.unstubAllEnvs();await fs.rm(directory,{recursive:true,force:true});});
async function upload(bytes:Buffer,type:'application/json'|'application/pdf'){const prepared=await prepareUploads(actor,repo,{purpose:'lesson',files:[{name:'lesson',type,size:bytes.length}]});const asset=(await repo.read()).assets.find(a=>a.id===prepared.assets[0].id)!;await putObject(actor,asset.originalObjectKey,bytes,type);return finalizeUpload(actor,repo,asset.id);}
describe('source-faithful lesson imports',()=>{
 it('parses actual JSON bytes rather than a client-supplied seed preview',async()=>{const source=structuredClone(curriculum.lessons[0]);source.title='Teacher-authored ribbon workshop';source.blocks[2].instructions='Our actual imported practice instruction, distinct from the seed.';const asset=await upload(Buffer.from(JSON.stringify(source)),'application/json');const result=await importLesson(actor,repo,{assetId:asset.id,lesson:curriculum.lessons[0]});expect(result.draft!.title).toBe(source.title);expect(result.draft!.blocks[2].instructions).toBe(source.blocks[2].instructions);expect(result.status).toBe('draft');expect((await repo.read()).planVersions).toHaveLength(2);});
 it('imports the prepared text PDF and ignores a malicious client text layer',async()=>{const bytes=await fs.readFile('public/demo/lesson-2026-09-23-original.pdf'),asset=await upload(bytes,'application/pdf');const result=await importLesson(actor,repo,{assetId:asset.id,extractedText:'INVENTED CLIENT CONTENT'});expect(result.errors).toEqual([]);expect(result.draft!.blocks).toHaveLength(5);expect(result.draft!.blocks[2].instructions).toContain('All students complete');expect(result.extractedText).not.toContain('INVENTED CLIENT CONTENT');});
 it('leaves an unmappable PDF as an empty editable draft instead of substituting the known lesson',async()=>{const asset=await upload(await fs.readFile('public/demo/baseline-template-v1.pdf'),'application/pdf');const result=await importLesson(actor,repo,{assetId:asset.id,extractedText:'September 23, 2026 fake seed preview'});expect(result.draft).toBeNull();expect(result.errors).not.toHaveLength(0);expect(result.extractedText).not.toContain('fake seed preview');});
 it('requires current-version confirmation before appending a replacement lesson',async()=>{const asset=await upload(Buffer.from(JSON.stringify(curriculum.lessons[0])),'application/json'),record=await importLesson(actor,repo,{assetId:asset.id});await expect(repo.transact(state=>confirmLessonImport(state,record.id,{expectedRevision:record.revision,lesson:record.draft!}))).rejects.toThrow(/already exists/);const current=(await repo.read()).plans.find(p=>p.id===record.draft!.lessonId)!;const saved=await repo.transact(state=>confirmLessonImport(state,record.id,{expectedRevision:record.revision,lesson:record.draft!,expectedPlanVersionId:current.currentVersionId}));expect(saved.previousVersionId).toBe(current.currentVersionId);expect(saved.sourceAssetId).toBe(asset.id);expect((await repo.read()).planVersions).toHaveLength(3);});
 it('keeps a schema-valid but overlong imported lesson for manual repair without saving it',async()=>{const source=structuredClone(curriculum.lessons[0]);source.blocks[2].minutes=25;const asset=await upload(Buffer.from(JSON.stringify(source)),'application/json'),result=await importLesson(actor,repo,{assetId:asset.id});expect(result.draft).toBeNull();expect(result.errors[0]).toMatch(/minute/);expect((await repo.read()).planVersions).toHaveLength(2);});
});
