import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import prepared from '../../lib/fixtures/extractions.json';
import { extractionSchema, type Batch, type Provenance } from '../../lib/contracts';
import { correctResponse, createBatch } from '../../lib/domain';
import { cancelJob, queueJob, retryJob, runNext } from '../../lib/server/jobs';
import { LocalRepository } from '../../lib/server/repository';
import { putObject } from '../../lib/server/storage';
import * as ai from '../../lib/server/ai';
const actor={id:'11111111-1111-4111-8111-111111111111',name:'Test teacher'};
const provenance:Provenance={mode:'fixture',modelId:'test-provider',promptVersion:'test-v1',generatedAt:'2026-09-19T12:00:00.000Z',inputFingerprint:'test'};
let directory:string,repo:LocalRepository;
beforeEach(async()=>{directory=await fs.mkdtemp(path.join(os.tmpdir(),'classcompass-jobs-'));vi.stubEnv('LOCAL_DATA_DIR',directory);vi.stubEnv('DATA_BACKEND','local');vi.stubEnv('AI_MODE','fixture');vi.stubEnv('APP_DEPLOYMENT','local');vi.stubEnv('VERCEL','');vi.stubEnv('AI_MAX_ATTEMPTS','3');repo=new LocalRepository(directory,actor.id);});
afterEach(async()=>{vi.useRealTimers();vi.unstubAllEnvs();await fs.rm(directory,{recursive:true,force:true});});
async function seed(studentId='stu-01'):Promise<Batch>{
 const [hash,entry]=Object.entries(prepared).find(([,entry])=>entry.templateId==='baseline-template-v1'&&entry.studentId===studentId)!;
 const key=`${actor.id}/${studentId}/original`;
 await putObject(actor,key,await fs.readFile(path.join(process.cwd(),'public/demo',`baseline-${studentId}.png`)),'image/png');
 return repo.transact(state=>{const time=new Date().toISOString(),assetId=`asset-${studentId}`;state.assets.push({id:assetId,ownerId:actor.id,createdAt:time,updatedAt:time,revision:1,purpose:'worksheet',name:`${studentId}.png`,status:'ready',mimeType:'image/png',byteCount:1,sha256:hash,originalObjectKey:key,templateId:entry.templateId});return createBatch(state,{kind:'baseline',templateId:entry.templateId,activityDate:'2026-09-22',submissions:[{studentId,assetId,support:{level:'independent',source:'teacher-recorded',note:'No help.'}}]});});
}
function provider(){return {...ai,extractWorksheet:vi.fn<typeof ai.extractWorksheet>(async input=>{const entry=prepared[input.assetHash as keyof typeof prepared];return{draft:extractionSchema.parse({templateId:entry.templateId,responses:entry.responses}),provenance};}),analyzeEvidence:vi.fn<typeof ai.analyzeEvidence>(async()=>({drafts:undefined,provenance})),proposeLesson:vi.fn<typeof ai.proposeLesson>(async()=>({changes:undefined,provenance}))};}
function deferred<T>(){let resolve!:(value:T)=>void;const promise=new Promise<T>(r=>{resolve=r;});return{promise,resolve};}
async function queue(batch:Batch,key?:string){return repo.transact(state=>queueJob(state,'analysis',batch.id,{expectedRevision:batch.revision},key));}

describe('durable analysis jobs',()=>{
 it('dispatches one bounded step per call and completes real domain analysis',async()=>{const batch=await seed(),job=await queue(batch),p=provider();await runNext(actor,repo,job.id,p);let state=await repo.read();expect(p.extractWorksheet).toHaveBeenCalledTimes(1);expect(p.analyzeEvidence).not.toHaveBeenCalled();expect(state.responses).toHaveLength(4);expect(state.findings).toHaveLength(0);expect(state.jobs[0].status).toBe('queued');await runNext(actor,repo,job.id,p);state=await repo.read();expect(p.analyzeEvidence).toHaveBeenCalledTimes(1);expect(state.findings[0].code).toBe('denominator_addition');expect(state.jobs[0].status).toBe('completed');await runNext(actor,repo,job.id,p);expect(p.extractWorksheet).toHaveBeenCalledTimes(1);});
 it('reuses queued work and stores every idempotency key without losing the batch job pointer',async()=>{const batch=await seed(),first=await queue(batch,'first'),same=await queue(batch,'second');expect(same.id).toBe(first.id);const state=await repo.read();expect(state.batches[0].latestJobId).toBe(first.id);expect(state.jobs).toHaveLength(1);expect(state.mutationKeys.filter(k=>k.operation===`analysis:${batch.id}`)).toHaveLength(2);await expect(repo.transact(state=>queueJob(state,'analysis',batch.id,{expectedRevision:2},'second'))).rejects.toThrow(/different inputs/);});
 it('discards a late analysis result when the teacher corrects source work',async()=>{const batch=await seed(),job=await queue(batch),p=provider();await runNext(actor,repo,job.id,p);const gate=deferred<Awaited<ReturnType<typeof ai.analyzeEvidence>>>(),started=deferred<void>();p.analyzeEvidence.mockImplementation(async()=>{started.resolve();return gate.promise;});const running=runNext(actor,repo,job.id,p);await started.promise;await repo.transact(state=>{const r=state.responses[0];correctResponse(state,r.id,{expectedRevision:r.revision,workingText:'1/2 = 3/6; 1/3 = 2/6; 3/6 + 2/6 = 5/6',answerText:'5/6',legibility:'clear',readingStatus:'resolved',reason:'Original page corrected.'});});gate.resolve({drafts:undefined,provenance});const result=await running;expect('discarded' in result&&result.discarded).toBe(true);const state=await repo.read();expect(state.jobs[0].status).toBe('cancelled');expect(state.responses[0].answerText).toBe('5/6');expect(state.responses[0].revision).toBe(2);expect(state.findings).toHaveLength(0);});
 it('cancelled extraction cannot commit a late provider response',async()=>{const batch=await seed(),job=await queue(batch),p=provider(),gate=deferred<Awaited<ReturnType<typeof ai.extractWorksheet>>>(),started=deferred<void>();const original=p.extractWorksheet.getMockImplementation()!;let value:Awaited<ReturnType<typeof ai.extractWorksheet>>;p.extractWorksheet.mockImplementation(async input=>{value=await original(input);started.resolve();return gate.promise;});const running=runNext(actor,repo,job.id,p);await started.promise;await repo.transact(state=>cancelJob(state,job.id));gate.resolve(value!);await running;const state=await repo.read();expect(state.responses).toHaveLength(0);expect(state.extractions).toHaveLength(0);expect(state.jobs[0].status).toBe('cancelled');});
 it('allows at most one in-flight provider call across the teacher classroom',async()=>{const batchA=await seed(),batchB=await seed('stu-02'),jobA=await queue(batchA),jobB=await queue(batchB),p=provider(),gate=deferred<Awaited<ReturnType<typeof ai.extractWorksheet>>>(),started=deferred<void>();const original=p.extractWorksheet.getMockImplementation()!;let value:Awaited<ReturnType<typeof ai.extractWorksheet>>;p.extractWorksheet.mockImplementation(async input=>{value=await original(input);started.resolve();return gate.promise;});const running=runNext(actor,repo,jobA.id,p);await started.promise;const second=await runNext(actor,repo,jobB.id,p);expect('waitReason' in second&&second.waitReason).toBe('Another step is processing.');expect(p.extractWorksheet).toHaveBeenCalledTimes(1);gate.resolve(value!);await running;});
 it('uses the four-second dispatch gate in live mode without issuing network calls in this test',async()=>{const batch=await seed(),job=await queue(batch),p=provider();vi.stubEnv('AI_MODE','live');await runNext(actor,repo,job.id,p);const result=await runNext(actor,repo,job.id,p);expect('waitReason' in result&&result.waitReason).toBe('Waiting for the model request interval.');expect(p.analyzeEvidence).not.toHaveBeenCalled();await repo.transact(state=>{state.lastDispatchAt=new Date(Date.now()-5000).toISOString();});await runNext(actor,repo,job.id,p);expect(p.analyzeEvidence).toHaveBeenCalledOnce();});
 it('honors Retry-After, preserves completed steps and exhausts the attempt budget',async()=>{const batch=await seed(),job=await queue(batch),p=provider();await runNext(actor,repo,job.id,p);p.analyzeEvidence.mockRejectedValue(new ai.AIError('AI_RATE_LIMIT','Please wait.',true,900000));const first=await runNext(actor,repo,job.id,p);expect(first.job.status).toBe('waiting_retry');expect(Date.parse(first.job.nextAttemptAt!)-Date.now()).toBeGreaterThan(890000);await runNext(actor,repo,job.id,p);expect(p.analyzeEvidence).toHaveBeenCalledTimes(1);for(let i=0;i<2;i++){await repo.transact(state=>{state.jobs[0].steps[1].nextAttemptAt=new Date(0).toISOString();});await runNext(actor,repo,job.id,p);}let state=await repo.read();expect(state.jobs[0].status).toBe('failed');expect(state.jobs[0].steps[1].attempts).toBe(3);expect(state.responses).toHaveLength(4);expect(state.findings).toHaveLength(0);await repo.transact(state=>retryJob(state,job.id));p.analyzeEvidence.mockResolvedValue({drafts:undefined,provenance});await runNext(actor,repo,job.id,p);state=await repo.read();expect(state.jobs[0].status).toBe('completed');expect(p.extractWorksheet).toHaveBeenCalledTimes(1);});
 it('blocks non-retryable quota failures until explicit retry',async()=>{const batch=await seed(),job=await queue(batch),p=provider();p.extractWorksheet.mockRejectedValue(new ai.AIError('AI_QUOTA','Free quota unavailable.',false));await runNext(actor,repo,job.id,p);await runNext(actor,repo,job.id,p);const state=await repo.read();expect(state.jobs[0].status).toBe('blocked');expect(p.extractWorksheet).toHaveBeenCalledTimes(1);});
});
