import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import sharp from 'sharp';
import { LocalRepository } from '../../lib/server/repository';
import { boundedBytes, finalizeUpload, getObject, hashBytes, MAX_FILE, prepareUploads, putObject } from '../../lib/server/storage';
const actor={id:'11111111-1111-4111-8111-111111111111',name:'Teacher'};
let directory:string,repo:LocalRepository;
beforeEach(async()=>{directory=await fs.mkdtemp(path.join(os.tmpdir(),'classcompass-storage-'));vi.stubEnv('LOCAL_DATA_DIR',directory);vi.stubEnv('DATA_BACKEND','local');vi.stubEnv('APP_DEPLOYMENT','local');vi.stubEnv('AI_MODE','fixture');vi.stubEnv('VERCEL','');repo=new LocalRepository(directory,actor.id);});
afterEach(async()=>{vi.unstubAllEnvs();await fs.rm(directory,{recursive:true,force:true});});
async function prepare(bytes:Buffer,type='image/png',purpose='worksheet'){const result=await prepareUploads(actor,repo,{purpose,...(purpose==='worksheet'?{templateId:'baseline-template-v1'}:{}),files:[{name:'uploaded-file',type,size:bytes.length}]});return (await repo.read()).assets.find(a=>a.id===result.assets[0].id)!;}
describe('private immutable evidence',()=>{
 it('verifies bytes, preserves source hashes and treats repeat finalize as idempotent',async()=>{const bytes=await fs.readFile('public/demo/baseline-stu-01.png'),asset=await prepare(bytes);await putObject(actor,asset.originalObjectKey,bytes,'image/png');const ready=await finalizeUpload(actor,repo,asset.id);expect(ready.status).toBe('ready');expect(ready.sha256).toBe(hashBytes(bytes));expect(ready.normalizedSha256).toBe(hashBytes(bytes));expect(ready.width!*ready.height!).toBeLessThanOrEqual(20_000_000);expect((await finalizeUpload(actor,repo,asset.id)).revision).toBe(ready.revision);await expect(putObject(actor,asset.originalObjectKey,Buffer.from('changed'),'image/png')).rejects.toThrow(/already stored/);expect(await getObject(actor,asset.originalObjectKey)).toEqual(bytes);});
 it('retries identical bytes and prevents simultaneous writers from replacing each other',async()=>{const key=`${actor.id}/race/original`,a=Buffer.alloc(10000,1),b=Buffer.alloc(10000,2);const results=await Promise.allSettled([putObject(actor,key,a,'image/png'),putObject(actor,key,b,'image/png')]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);const saved=await getObject(actor,key);expect(saved.equals(a)||saved.equals(b)).toBe(true);await expect(putObject(actor,key,saved,'image/png')).resolves.toBeUndefined();expect((await fs.readdir(path.join(directory,'assets',actor.id,'race'))).filter(f=>f.endsWith('.tmp'))).toEqual([]);});
 it('rejects MIME spoofing, declared-size mismatch and decompression dimensions',async()=>{const fake=Buffer.from('not a PNG'),fakeAsset=await prepare(fake);await putObject(actor,fakeAsset.originalObjectKey,fake,'image/png');await expect(finalizeUpload(actor,repo,fakeAsset.id)).rejects.toThrow(/clear PNG/);const actual=await fs.readFile('public/demo/baseline-stu-01.png'),wrong=await prepare(actual);await repo.transact(s=>{s.assets.find(a=>a.id===wrong.id)!.byteCount++;});await putObject(actor,wrong.originalObjectKey,actual,'image/png');await expect(finalizeUpload(actor,repo,wrong.id)).rejects.toThrow(/declared size/);const huge=await sharp({create:{width:6000,height:4000,channels:3,background:'white'}}).png().toBuffer(),hugeAsset=await prepare(huge);await putObject(actor,hugeAsset.originalObjectKey,huge,'image/png');await expect(finalizeUpload(actor,repo,hugeAsset.id)).rejects.toThrow(/20 megapixels/);expect((await repo.read()).assets.every(a=>a.status==='pending')).toBe(true);});
 it('enforces owner prefixes and blocks traversal before filesystem access',async()=>{await expect(putObject(actor,'other-owner/file',Buffer.from('x'),'image/png')).rejects.toThrow(/not found/);await expect(getObject(actor,`${actor.id}/../outside`)).rejects.toThrow(/Invalid asset path/);await expect(putObject(actor,`${actor.id}/../outside`,Buffer.from('x'),'image/png')).rejects.toThrow(/Invalid asset path/);});
 it('deduplicates preparation by request key and rejects a changed request under that key',async()=>{const input={purpose:'worksheet',templateId:'baseline-template-v1',files:[{name:'work.png',type:'image/png',size:10}]};const first=await prepareUploads(actor,repo,input,'upload-key'),second=await prepareUploads(actor,repo,input,'upload-key');expect(second.assets.map(a=>a.id)).toEqual(first.assets.map(a=>a.id));expect((await repo.read()).assets).toHaveLength(1);await expect(prepareUploads(actor,repo,{...input,files:[{name:'different.png',type:'image/png',size:10}]},'upload-key')).rejects.toThrow(/different files/);await expect(prepareUploads(actor,repo,{...input,files:[{name:'large.png',type:'image/png',size:MAX_FILE+1}]})).rejects.toThrow();});
 it('enforces actual streamed request length even when Content-Length is absent or false',async()=>{await expect(boundedBytes(new Request('http://localhost/upload',{method:'POST',body:'123456789',headers:{'content-length':'0'}}),8)).rejects.toThrow(/upload size/);await expect(boundedBytes(new Request('http://localhost/upload',{method:'POST',body:'x',headers:{'content-length':'100'}}),8)).rejects.toThrow(/upload size/);expect((await boundedBytes(new Request('http://localhost/upload',{method:'POST',body:'12345678'}),8)).length).toBe(8);});
});
