import { describe, expect, it } from 'vitest';
import prepared from '../../lib/fixtures/extractions.json';
import { extractionSchema, type AppState, type Batch, type Provenance } from '../../lib/contracts';
import { curriculum, getQuestion } from '../../lib/curriculum';
import { analyzeBatch, applyProposal, checkMath, correctResponse, correctSupport, createBatch, createInitialState, editFinding, editProposal, generateProposal, ingestExtraction, parseFraction, proposalAfter, reviewFindings, validateLesson } from '../../lib/domain';

const provenance: Provenance={mode:'fixture',modelId:'prepared-fixture',promptVersion:'test-v1',generatedAt:'2026-09-19T12:00:00.000Z',inputFingerprint:'test'};
function seedBatch(state:AppState,kind:'baseline'|'followup'='baseline') {
  const templateId=kind==='baseline'?'baseline-template-v1':'followup-template-v1';
  const entries=Object.entries(prepared).filter(([,entry])=>entry.templateId===templateId);
  for(const [hash,entry] of entries)state.assets.push({id:`asset-${kind}-${entry.studentId}`,ownerId:state.ownerId,createdAt:provenance.generatedAt,updatedAt:provenance.generatedAt,revision:1,purpose:'worksheet',name:'sample.png',status:'ready',mimeType:'image/png',byteCount:10,originalObjectKey:hash,sha256:hash,templateId});
  const batch=createBatch(state,{kind,templateId,activityDate:kind==='baseline'?'2026-09-22':'2026-09-24',submissions:entries.map(([,entry])=>({studentId:entry.studentId,assetId:`asset-${kind}-${entry.studentId}`,support:{level:'independent',source:'teacher-recorded',note:'No help recorded.'}}))});
  for(const submissionId of batch.submissionIds){const submission=state.submissions.find(s=>s.id===submissionId)!;const [hash,entry]=entries.find(([,e])=>e.studentId===submission.studentId)!;ingestExtraction(state,{submissionId,draft:extractionSchema.parse({templateId,responses:entry.responses}),assetHash:hash,provenance});}
  analyzeBatch(state,{batchId:batch.id,provenance});return batch;
}
function confirmBatch(state:AppState,batch:Batch){const findings=state.findings.filter(f=>f.batchId===batch.id&&f.status==='candidate');return reviewFindings(state,{items:findings.map(f=>({findingId:f.id,expectedRevision:f.revision,decision:'confirm'})),acknowledgeClearReadings:true});}
function correctBaseline(state:AppState,batch:Batch){
 const finleySubmission=state.submissions.find(s=>s.batchId===batch.id&&s.studentId==='stu-06')!,response=state.responses.find(r=>r.submissionId===finleySubmission.id&&r.questionId==='q-03')!;
 correctResponse(state,response.id,{expectedRevision:response.revision,workingText:'2/5 = 4/10; 4/10 + 1/10 = 5/10 = 1/2',answerText:'1/2',legibility:'clear',readingStatus:'resolved',reason:'The original page reads one half.'});
 const gray=state.submissions.find(s=>s.batchId===batch.id&&s.studentId==='stu-07')!;
 correctSupport(state,gray.id,{expectedRevision:gray.revision,support:{level:'supported',source:'teacher-corrected',note:'I prompted a common denominator.'},reason:'Record the assistance given.'});
 analyzeBatch(state,{batchId:batch.id,provenance});
}
function proposal(state:AppState,lessonId='lesson-2026-09-23'){return generateProposal(state,lessonId,{basePlanVersionId:state.plans.find(p=>p.id===lessonId)!.currentVersionId,expectedEvidenceRevision:state.classroom.evidenceRevision,expectedCalendarRevision:state.classroom.calendarRevision,provenance});}
function applyInput(state:AppState,p:ReturnType<typeof proposal>){return{expectedRevision:p.revision,basePlanVersionId:p.basePlanVersionId,expectedEvidenceRevision:state.classroom.evidenceRevision,expectedCalendarRevision:state.classroom.calendarRevision,selectedChangeIds:p.changes.map(c=>c.id)};}

describe('exact fraction checks',()=>{
 it('accepts unreduced 3/6 and safe units; never evaluates source text',()=>{expect(checkMath(getQuestion('fq02'),'1/3 = 2/6; 1/6 + 2/6 = 3/6','3/6 meter','clear').status).toBe('correct');expect(parseFraction('1/0')).toBeNull();expect(parseFraction('1 1/2')).toBeNull();expect(parseFraction('globalThis.process.exit()')).toBeNull();expect(parseFraction('10001/2')).toBeNull();});
 it('distinguishes internally inconsistent renaming from a reviewable incorrect sum',()=>{expect(checkMath(getQuestion('q-03'),'2/5 = 4/10; 4/10 + 1/10 = 5/10 = 1/5','1/5','uncertain').contradictions).toHaveLength(1);const error=checkMath(getQuestion('q-01'),'1/2 + 1/3 = 2/5','2/5','clear');expect(error.denominatorAddition).toBe(true);expect(error.contradictions).toEqual([]);});
 it('does not diagnose a denominator pattern from only a wrong final answer',()=>{expect(checkMath(getQuestion('q-01'),'','2/5','clear').denominatorAddition).toBe(false);});
});
describe('teacher evidence loop',()=>{
 it('derives candidates from effective work, while withholding plan changes until review',()=>{const state=createInitialState('teacher');const batch=seedBatch(state);expect(state.findings.filter(f=>f.code==='denominator_addition')).toHaveLength(3);expect(state.findings.find(f=>f.studentId==='stu-06')!.code).toBe('ambiguous_transcription');expect(()=>proposal(state)).toThrow(/Confirm/);expect(state.observations).toHaveLength(0);expect(state.planVersions).toHaveLength(curriculum.lessons.length);expect(batch.submissionIds).toHaveLength(8);});
 it('corrects handwriting and help, preserves originals, and derives 3/2/3 lanes',()=>{const state=createInitialState('teacher'),batch=seedBatch(state);const extractionSnapshot=JSON.stringify(state.extractions);correctBaseline(state,batch);confirmBatch(state,batch);const p=proposal(state),practice=proposalAfter(state,p).blocks.find(b=>b.id==='practice')!;expect(practice.lanes!.map(l=>l.studentIds.length)).toEqual([3,2,3]);expect(practice.lanes![1].studentIds).toEqual(['stu-07','stu-08']);expect(state.findings.find(f=>f.studentId==='stu-07'&&f.status==='confirmed')!.observationStatus).toBe('supported');expect(JSON.stringify(state.extractions)).toBe(extractionSnapshot);expect(state.responseRevisions).toHaveLength(1);expect(proposalAfter(state,p).blocks.reduce((n,b)=>n+b.minutes,0)).toBe(45);});
 it('review conflicts are atomic and repeated confirmation creates no duplicate observation',()=>{const state=createInitialState('teacher'),batch=seedBatch(state),findings=state.findings.slice(0,2);expect(()=>reviewFindings(state,{items:findings.map((f,i)=>({findingId:f.id,expectedRevision:f.revision+i,decision:'confirm'})),acknowledgeClearReadings:true})).toThrow(/changed/);expect(state.observations).toHaveLength(0);expect(state.readingReviews).toHaveLength(0);confirmBatch(state,batch);const count=state.observations.length;reviewFindings(state,{items:state.findings.filter(f=>f.status==='confirmed').map(f=>({findingId:f.id,expectedRevision:f.revision,decision:'confirm'})),acknowledgeClearReadings:true});expect(state.observations).toHaveLength(count);});
 it('uncertain readings cannot be approved as independent success by bulk acknowledgement',()=>{const state=createInitialState('teacher'),batch=seedBatch(state),f=state.findings.find(f=>f.studentId==='stu-06')!;editFinding(state,f.id,{expectedRevision:f.revision,objectiveId:f.objectiveId,code:'equivalent_fraction_reasoning',claimScope:'independent_performance',explanation:'Proposed independent success.',evidence:f.evidence,limitations:[],suggestedNextStep:'extension',reason:'Review a different interpretation.'});expect(()=>reviewFindings(state,{items:[{findingId:f.id,expectedRevision:f.revision,decision:'confirm'}],acknowledgeClearReadings:true})).toThrow(/Resolve uncertain/);expect(state.observations).toHaveLength(0);expect(batch.id).toBeTruthy();});
 it('semantic override withdraws the earlier observation and requires fresh confirmation',()=>{const state=createInitialState('teacher'),batch=seedBatch(state);confirmBatch(state,batch);const f=state.findings.find(f=>f.studentId==='stu-01'&&f.status==='confirmed')!,p=proposal(state);editFinding(state,f.id,{expectedRevision:f.revision,objectiveId:f.objectiveId,code:'other_teacher_finding',claimScope:'evidence_quality',explanation:'I need an oral explanation before deciding the cause.',evidence:f.evidence,limitations:['Verify the interpretation.'],suggestedNextStep:'gather_evidence',reason:'The interpretation changed.'});expect(f.status).toBe('candidate');expect(state.observations.find(o=>o.findingId===f.id)!.superseded).toBe(true);expect(p.status).toBe('stale');expect(f.originalDraft.code).toBe('denominator_addition');});
 it('a correction stales dependent work without rewriting accepted instruction or unrelated findings',()=>{const state=createInitialState('teacher'),batch=seedBatch(state);correctBaseline(state,batch);confirmBatch(state,batch);const p=proposal(state),result=applyProposal(state,p.id,applyInput(state,p),{idempotencyKey:'apply'}),saved=JSON.stringify(state.planVersions.find(v=>v.id===result.planVersionId));const response=state.responses.find(r=>state.submissions.find(s=>s.id===r.submissionId)!.studentId==='stu-01')!;correctResponse(state,response.id,{expectedRevision:response.revision,workingText:response.workingText,answerText:response.answerText,legibility:response.legibility,readingStatus:'resolved',reason:'Recheck this source.'});expect(state.findings.find(f=>f.studentId==='stu-01')!.status).toBe('stale');expect(state.findings.some(f=>f.studentId==='stu-02'&&f.status==='confirmed')).toBe(true);expect(JSON.stringify(state.planVersions.find(v=>v.id===result.planVersionId))).toBe(saved);});
});
describe('atomic plans and continued evidence',()=>{
 it('applies selected changes exactly once and preserves 8+37 calendar allocation and locked date',()=>{const state=createInitialState('teacher'),batch=seedBatch(state);correctBaseline(state,batch);confirmBatch(state,batch);const p=proposal(state),input=applyInput(state,p),result=applyProposal(state,p.id,input,{idempotencyKey:'same'});expect(applyProposal(state,p.id,input,{idempotencyKey:'same'})).toEqual(result);expect(state.planVersions).toHaveLength(curriculum.lessons.length+1);expect(state.calendarEntries.find(e=>e.date==='2026-09-24')!.checkpoint!.minutes).toBe(8);expect(state.calendarEntries.find(e=>e.date==='2026-09-24')!.minutes).toBe(45);expect(state.calendarEntries.find(e=>e.locked)!.date).toBe('2026-10-02');expect(()=>applyProposal(state,p.id,{...input,selectedChangeIds:[]},{idempotencyKey:'same'})).toThrow(/different selection/);});
 it('rejects invalid time, duplicate roster and extension assignments without partial application',()=>{const state=createInitialState('teacher'),batch=seedBatch(state);correctBaseline(state,batch);confirmBatch(state,batch);const p=proposal(state);const changes=structuredClone(p.changes),practice=changes.find(c=>c.operation==='replace_practice')!;if(practice.operation!=='replace_practice')throw Error();practice.payload.block.lanes![0].studentIds.push('stu-04');expect(()=>editProposal(state,p.id,{expectedRevision:p.revision,changes,reason:'Invalid duplicate'})).toThrow();expect(p.revision).toBe(1);expect(state.planVersions).toHaveLength(curriculum.lessons.length);const snapshot=structuredClone(curriculum.lessons[0]);snapshot.blocks[2].minutes=36;expect(()=>validateLesson(state,snapshot)).toThrow(/minute/);});
 it('keeps the original when zero changes are selected',()=>{const state=createInitialState('teacher'),batch=seedBatch(state);confirmBatch(state,batch);const p=proposal(state),result=applyProposal(state,p.id,{...applyInput(state,p),selectedChangeIds:[]});expect(result.keptOriginal).toBe(true);expect(p.status).toBe('discarded');expect(state.planVersions).toHaveLength(curriculum.lessons.length);expect(state.materialSets).toHaveLength(0);});
 it('uses fresh September 24 work for September 25, returns improving students and preserves supported history',()=>{const state=createInitialState('teacher'),baseline=seedBatch(state);correctBaseline(state,baseline);confirmBatch(state,baseline);const first=proposal(state);const applied=applyProposal(state,first.id,applyInput(state,first));const preserved=JSON.stringify(state.planVersions.find(v=>v.id===applied.planVersionId));const followup=seedBatch(state,'followup');confirmBatch(state,followup);const second=proposal(state,'lesson-2026-09-25'),lanes=proposalAfter(state,second).blocks.find(b=>b.id==='practice')!.lanes!;expect(lanes[0].studentIds).toEqual(['stu-03']);expect(lanes[1].studentIds).toEqual(['stu-01','stu-02','stu-07','stu-08']);expect(lanes[2].studentIds).toEqual(['stu-04','stu-05','stu-06']);expect(JSON.stringify(state.planVersions.find(v=>v.id===applied.planVersionId))).toBe(preserved);expect(state.observations.filter(o=>o.studentId==='stu-07').map(o=>o.observationStatus)).toEqual(['supported','independent']);expect(()=>proposal(state)).toThrow(/Do not rewrite/);});
});
